export const TOGGLE_CHECKING_OUT = 'TOGGLE_CHECKING_OUT';
export const SET_CURRENT_USER_INFO = 'SET_CURRENT_USER_INFO';
export const GET_CURRENT_USER_INFO = 'GET_CURRENT_USER_INFO';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const SET_ITEM_DETAILS = 'SET_ITEM_DETAILS';
export const SET_SHIPPING_COST = 'SET_SHIPPING_COST';
export const SET_TAX_RATE = 'SET_TAX_RATE';